# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - GiEnJulTest1(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run test --if-present
      working-directory: Frontend/gi-en-jul

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: GiEnJulTest1
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_77464987B9E74190BC5265CFC7E01F38 }}
        package: Frontend/gi-en-jul

