name: Deploy backend service - ASP.NET CORE 3.1 APP

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
  workflow_dispatch:
      
env:
  AZURE_WEBAPP_NAME: gienjultestapi
  AZURE_WEBAPP_PACKAGE_PATH: 'Pack'
  DOTNET_VERSION: '3.1.409'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Run dotnet build and publish
    - name: dotnet build, test and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test
        dotnet publish ApiApp -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      working-directory: Backend
      
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND_TEST }}
        package: Backend/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

